apiVersion: v1
kind: Pod
metadata:
  name: test-acr-pull
spec:
  containers:
  - name: acrprojectlearn2024
    image: acrprojectlearn2024.azurecr.io/hello-world:latest
  imagePullSecrets: []  # We're testing if the managed identity works without secrets
