apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-p8
  labels:
    app: backend-p8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-p8
  template:
    metadata:
      labels:
        app: backend-p8
    spec:
      containers:
      - name: backend
        image: aksdev007.azurecr.io/aks-backend-p8:IMAGE_TAG_PLACEHOLDER # REPLACE WITH YOUR ACR LOGIN SERVER
        ports:
        - containerPort: 5000
        imagePullPolicy: Always # <--- THIS IS THE CORRECTED LINE
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service-p8
spec:
  selector:
    app: backend-p8
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
