name: Build, Push, and Deploy Project 8 to AKS

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
    paths:
      - 'Project8/**' # Only trigger if changes are within the Project8 folder

env:
  RESOURCE_GROUP: aks-dev-rg      # Your Azure Resource Group name
  AKS_CLUSTER_NAME: myakscluster  # Your AKS cluster name
  ACR_NAME: aksdev007          # Your Azure Container Registry name
  ACR_LOGIN_SERVER: aksdev007.azurecr.io # Your ACR login server

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Build and push Frontend image
      run: |
        docker build ./Project8/frontend -t ${{ env.ACR_LOGIN_SERVER }}/aks-frontend-p8:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/aks-frontend-p8:${{ github.sha }}

    - name: Build and push Backend image
      run: |
        docker build ./Project8/backend -t ${{ env.ACR_LOGIN_SERVER }}/aks-backend-p8:${{ github.sha }}
        docker push ${{ env.ACR_LOGIN_SERVER }}/aks-backend-p8:${{ github.sha }}

  deploy-to-aks:
    needs: build-and-push-images # This job depends on successful image builds and pushes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS credentials
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}

    - name: Update and Deploy Frontend to AKS
      run: |
        # Use sed to replace the placeholder with the actual GitHub SHA tag
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" Project8/frontend-deployment.yaml
        kubectl apply -f Project8/frontend-deployment.yaml
        kubectl rollout restart deployment/frontend-deployment-p8 -n default

    - name: Update and Deploy Backend to AKS
      run: |
        # Use sed to replace the placeholder with the actual GitHub SHA tag
        sed -i "s|IMAGE_TAG_PLACEHOLDER|${{ github.sha }}|g" Project8/backend-deployment.yaml
        kubectl apply -f Project8/backend-deployment.yaml
        kubectl rollout restart deployment/backend-deployment-p8 -n default
